# Generated by Django 2.2 on 2019-06-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default='2019-06-01 08:32:35')),
                ('updated_at', models.DateTimeField(default='2019-06-01 08:32:35')),
            ],
            options={
                'db_table': 'todos',
                'ordering': ['-created_at'],
            },
        ),
    ]
